Some updates to fix Errors
aMidnightNova/ValheimVRM pull request #6
Opened 2024-01-25 17:58 UTC by Fehdra

1.1.3.0 to 1.2.4.0 in the main

changes to prevent a NullReferenceException i was having so added  && vrm != null) in ValheimVRM.cs

Fixed some game errors for VRMEyePositionSync

2024-01-25 18:13 UTC, aMidnightNova requested changes
Overall looks good, just a few minor things. I will test this later today or tomorrow.

2024-01-25 18:13 UTC, aMidnightNova commented on ValheimVRM/ValheimVRM.cs
> +	// To prevent a NullReferenceException, you should check if vrm is not null before attempting to access its components. Here's the modified code with a null check: var lodGroup = vrm.GetComponent<LO
Move this to the PR notes.

2024-01-25 18:13 UTC, aMidnightNova commented on ValheimVRM/ValheimVRM.cs
> +            if (VrmManager.PlayerToVrmInstance.TryGetValue((Player)__instance, out var vrm) && vrm != null)
you can put the here a note about "null check before accessing components"

2024-01-25 18:13 UTC, aMidnightNova commented on ValheimVRM/ValheimVRM.cs
> +                if (lodGroup != null)
Same for here about the new null check for log group.

E.G. // avoid reference errors use null check for lod.

2024-01-26 00:40 UTC, Fehdra reviewed
Like this?  :}

2024-01-29 04:46 UTC, aMidnightNova commented
Everything seams to work, merging.

2024-01-29 04:47 UTC, merged